source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'LoginKit_Example' do
  pod 'LoginKit', :path => '../'
end

target 'LoginKit_Tests' do
  pod 'LoginKit', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
