source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LoginKit_Example' do
  pod 'LoginKit', :path => '../'
end

target 'LoginKit_Tests' do
  pod 'LoginKit', :path => '../'

  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '4.0.0'
end
