# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
xcode_project: Example/LoginKit.xcodeproj
podfile: Example/Podfile
osx_image: xcode7
xcode_sdk: iphonesimulator9.0
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- pod lib lint --allow-warnings
# - set -o pipefail && xcodebuild test -workspace Example/LoginKit.xcworkspace -scheme LoginKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
